server.port=8088
spring.application.name=notification-service

# Mail Configuration (Placeholders)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=urbanvogue056@gmail.com
spring.mail.password=gfsu hqtb mpfw najm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# RabbitMQ Configuration
spring.rabbitmq.addresses=amqps://hapeoftl:DT1UlgUY7CpYUZRgx2O7OgmYjJxOoikz@raccoon.lmq.cloudamqp.com/hapeoftl

# Tracing Configuration
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
